freemint/libcmini

sources/strerror_r.c
=> Define _GNU_SOURCE to avoid pulling in a incompatible

sources/atexit.c, sources/realloc.c
memory.h and unistd.h are only provided by MintLib. Unconditionally
including them will require the mintlib headers, and may pull in
other headers resulting in redefinitions
=> Only include <memory.h> for MintLib compatibility

Makefile, sources/doprnt.c
all dirs and flags now extracted from `gcc -print-multi-lib`
egrep is deprecated use `grep -E`
all options now invokeable with "=Y" or "=yes"
NOTE: tests no touched
=> remove hardcoded multilib dirs from Makefile

sources/atoi.c, sources/atol.c
Spec requires that atoi and atol ignore whitespaces before the number.
=> Fix atoi and atol as per spec

sources/strlen.c
Strlen calculates the string length with pointer math, but unfortunatly
the loop uses post-increment event when terminating character is detected.
This leads to the pointer going past the terminating character and causing
off by one error when calculating the length.
=> Fix strlen

sources/strcmp.c, sources/strlen.c, sources/strncmp.c
I'd appreciate @mfro0  if you could look at my strncmp findings.
=> Revert errounous change in strlen and workaround a bug(?) in a compiler?

sources/scanf.c
libcmini's current scanf implementation only returns 0 (in case of any failure) or 1 (in case of success). However, scanf (and fscanf, sscanf, ...) is supposed to return the number of input items that were matched.
Consider the following test program:
```c
#include <stdio.h>
int main(void) {
int data1, data2, data3;
int ret;
ret = sscanf("123 456 789", "%d", &data1);
printf("Found %d item(s)\n", ret);
ret = sscanf("123 456 789", "%d %d", &data1, &data2);
printf("Found %d item(s)\n", ret);
ret = sscanf("123 456 789", "%d %d %d", &data1, &data2, &data3);
printf("Found %d item(s)\n", ret);
ret = sscanf("123 FOO 789", "%d %d %d", &data1, &data2, &data3);
printf("Found %d item(s)\n", ret);
ret = sscanf("123 456 789", "%d FOO %d", &data1, &data2);
printf("Found %d item(s)\n", ret);
return 0;
} …
```
=> scanf - Return number of matched input items

sources/vsnprintf.c, sources/vsprintf.c
Why increment stream.xstring and subtract 1 upon return?
=> Crap in vs(n)printf.c removed

sources/atof.c
The man page says:
> The call atof(str) shall be equivalent to:
>            strtod(str,(char **)NULL),
> except that the handling of errors may differ.
So, why not simply call strtod() instead of making rudimentary parsing?
=> atof() - Simply call strtod()

sources/main.c
1) At least fgetc() checks FILE.__mode.__read to be set, so reading charactes from stdin isn't possible without setting it to a value != 0.
2) FILE.__pushback must be set to EOF to indicate that there are no pushed back characters.
Don't get confused by the seemingly changed code. My editor removes trailing whitespaces when saving files. The actual changes are at the bottom of the file (line 444ff).
=> Added missing values on initialization of stdin, stdout and stderr

include/time.h, sources/gmtime.c, sources/localtime.c, sources/mktime.c, sources/strftime.c, sources/time.c, sources/tzset.c
New functions in time.h: gmtime() and tzset()
New global variables in time.h: localtime, tzname[]
Timezone support is implemented with parsing the TZ environment variable as described here:
https://users.pja.edu.pl/~jms/qnx/help/watcom/clibref/global_data.html#TheTZEnvironmentVariable
Due to the lack of DST support, the rule part of the TZ variable will not be interpreted.
The time functions assume the system time to be local time rather than UTC, because that is the usual setup (see comment in time.h -> GMT_BIOS_CLOCK).
Some TZ examples:
Central European Time: CET-1
Central European Summer Time: CEST-2
Afghanistan Time: AFT-4:30
Japanese Standard Time: JST-9
Eastern Standard Time: EST+5
Pacific Standard Time: PST+9
Greenwich Mean Time: GMT
The offset must be given in time to add to reach …
=> Add timezone support

.gitignore, Makefile
The intention is to provide a way to play around with the configuration variables such as ONLY_68K etc. and CFLAGS without modifying Makefile and maybe forgetting to undo such changes.
Make.config.local is now added to .gitignore to ensure that these local configuration will not be pushed to the repository.
=> Add include of optional Make.config.local to Makefile

sources/bcopy.S
When size is 0, the stack must not be corrected before returning!
Fixes #82
=> Fix bug that causes memcpy() etc. to crash when size parameter is 0

sources/strftime.c
The format specifiers "%a" and "%A" would otherwise lead to bombs in case of tp->tm_wday being outside [0..6]. Same applies to "%b" and "%B" and tp->tm_mon being outside [0..11].
=> Check for valid weekday/month before accessing corresponding name array

sources/strrchr.c
The function started searching one byte behind the terminating null character.
=> Fix bug in strrchr()

include/stdio.h, sources/fdopen.c, sources/fflush.c, sources/fopen.c, sources/fputs.c, sources/fseek.c, sources/fwrite.c, sources/rewind.c, sources/stdio.c, sources/vfprintf.c
Issue #91
Maybe we can get together at last. I removed the conversion from `fputs()` and `vfprintf()` and had a look at what Mintlib does (see `__stdio_text_write()` in `stdio/sysd-stdio.c`).
I introduced a preprocessor macro `STDIO_MAP_NEWLINE` which has to be defined to enable the automatic conversion. It is disabled by default and has to be enabled explicitly e.g. in `Make.config.local`:
`CFLAGS	= -Werror -O2 -fomit-frame-pointer -DSTDIO_MAP_NEWLINE
`
The conversion is done similar to Mintlib, but in `fwrite()` and only there. The resulting binaries should be smaller no matter if you compile with automatic conversion or not. A simple `printf("Hello World!\n");` will have 12663 vs. 12966 bytes.
=> stdio: Map newline

sources/opendir.c
=> opendir() possible access before an array.

Makefile
PREFIX_FOR_STARTUP is set to DESTDIR/usr/lib by default.
This fixes building with `make PREFIX_FOR_STARTUP=...`.
=> Use PREFIX_FOR_STARTUP instead of DESTDIR

include/stdio.h, sources/open.c
Added some macro definitions from mintlib's fcntl.h to stdio.h, so open.c does not need to include fcntl.h anymore.
=> Remove using mintlib's fcntl.h

sources/stat.c
Fixes issue #108 and solves the inconsistent use of mintlib's struct stat instead of libcmini's version.
=> Set st_atime, st_mtime and st_ctime correctly and remove inclusion of mintlib header files

sources/getopt.c
- add missing option arguments (#111)
- fix some bugs regarding opterr, optarg and optopt
- return '?' or ':' in case of error in respect of first character of optstring and type of error
=> Fix getopt() implementation

sources/strncpy.c
=> Write additional null bytes to dst to ensure that a total of max bytes are written

sources/remove.c
Ddelete() may return -ENOTDIR (negative), but never ENOTDIR (positive).
=> Check for -ENOTDIR
